apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.existingSecret }}
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "applesupport.labels" . | nindent 4 }}
type: Opaque
stringData:
  postgres-password: {{ .Values.secrets.postgresPassword | quote }}
  jwt-secret-key: {{ .Values.secrets.jwtSecretKey | quote }}
  openai-api-key: {{ .Values.secrets.openaiApiKey | quote }}
  groq-api-key: {{ .Values.secrets.groqApiKey | quote }}

