"""
Analytics API endpoints for operations dashboards, accuracy trends, and efficiency metrics.
"""

from fastapi import APIRouter, Depends, Query
from sqlalchemy.ext.asyncio import AsyncSession
from app.api.deps import get_current_user
from app.db.session import get_db
from app.models.user import User
from app.schemas.analytics import (
    AnalyticsOverview,
    ConfidenceTrendResponse,
    FeedbackSummaryResponse,
    IntentDistributionResponse,
    TimeSavedResponse,
)
from app.services.analytics_service import AnalyticsService

router = APIRouter(prefix="/analytics", tags=["Analytics"])


@router.get("/overview", response_model=AnalyticsOverview)
async def get_analytics_overview(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Retrieve operational overview metrics for the executive and agent dashboard."""
    service = AnalyticsService(db)
    return await service.get_overview()


@router.get("/intent-distribution", response_model=IntentDistributionResponse)
async def get_intent_distribution(
    period: str = Query("week", description="Aggregation period: 'day', 'week', 'month'"),
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Retrieve breakdown of customer query intent categories."""
    service = AnalyticsService(db)
    return await service.get_intent_distribution(period=period)


@router.get("/confidence-over-time", response_model=ConfidenceTrendResponse)
async def get_confidence_trend(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Retrieve time-series data of model classification confidence."""
    service = AnalyticsService(db)
    return await service.get_confidence_trend()


@router.get("/feedback-summary", response_model=FeedbackSummaryResponse)
async def get_feedback_summary(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Retrieve agent draft approval vs editing vs rejection breakdown per intent."""
    service = AnalyticsService(db)
    return await service.get_feedback_summary()


@router.get("/time-saved", response_model=TimeSavedResponse)
async def get_time_saved(
    db: AsyncSession = Depends(get_db),
    current_user: User = Depends(get_current_user),
):
    """Calculate estimated hours and cost savings generated by AI co-pilot drafting."""
    service = AnalyticsService(db)
    return await service.get_time_saved()

